package constants

// 日志模板集中管理：任何业务字段变更都必须同步修改对应模板与调用处。
const (
	LogUserRegisterStart       = "user register start"
	LogUserRegisterSuccess     = "user register success"
	LogUserLoginSuccess        = "user login success"
	LogUserLoginFailed         = "user login failed"
	LogUserProfileUpdate       = "user profile update"
	LogClientCreateSuccess     = "client create success"
	LogClientUpdateSuccess     = "client update success"
	LogClientDeleteSuccess     = "client delete success"
	LogCaseCreateSuccess       = "case create success"
	LogCaseCreateFailed        = "case create failed"
	LogCaseUpdateSuccess       = "case update success"
	LogCaseStatusChangeSuccess = "case status change success"
	LogCaseStatusChangeFailed  = "case status change failed"
	LogCaseAssignSuccess       = "case assign success"
	LogCaseAssignFailed        = "case assign failed"
	LogDocumentUploadSuccess   = "document upload success"
	LogDocumentUploadFailed    = "document upload failed"
	LogDocumentDeleteSuccess   = "document delete success"
	LogBillingCreateSuccess    = "billing create success"
	LogBillingCreateFailed     = "billing create failed"
	LogBillingPaidSuccess      = "billing paid success"
	LogBillingPaidFailed       = "billing paid failed"
	LogBillingInvoicedSuccess  = "billing invoiced success"
	LogBillingVoidSuccess      = "billing void success"
	LogBillingSummary          = "billing summary"
	LogAuditWriteFailed        = "audit log write failed"
	LogUploadFileSuccess       = "upload file success"
	LogUploadFileFailed        = "upload file failed"
	LogRateLimitHit            = "rate limit hit"
	LogCommentCreateFailed     = "unused comment template"
)
